export const OP_Fruit_list_URL = "https://api.api-onepiece.com/v2/fruits/en"
export const OP_CHARACTER_SEARCH_URL = "https://api.api-onepiece.com/v2/characters/en/search/"
export const OP_CHARACTER_LIST_URL = "https://api.api-onepiece.com/v2/characters/en"
export const OP_BOAT_SEARCH_URL = "https://api.api-onepiece.com/v2/boats/en/search/"
export const OP_BOAT_LIST_URL = "https://api.api-onepiece.com/v2/boats/en"
